version: '3.9'
services:
  store-fr:
    build: .
  # ports:
  #    - "2000-4000:3000"
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - store-fr
    ports:
      - 3000:3000
